#!/usr/bin/env bash
# This file gives information about a domain specified in arguments
print_function() {
    echo -n "The subdomain $1 is a "
    dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -n1 | cut -b 1- | awk '{printf $4}'
    echo -n " record and points to "
    dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $5}'
}
if [ "$#" -gt 1 ]; then
    print_function "$2" "$1"
else
    print_function "www" "$1"
    print_function "lb-01" "$1"
    print_function "web-01" "$1"
    print_function "web-02" "$1"
fi;
