#!/usr/bin/env bash
# Script to transfer files specified
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  PATH_TO_FILE=$1
  IP=$2
  USERNAME=$3
  PATH_TO_SSH_KEY=$4
  scp -i "$PATH_TO_SSH_KEY" "$USERNAME@$IP:/$PATH_TO_FILE" ~/
fi
