#!/usr/bin/env bash
# Script to install NGINX in Ubuntu 16
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "y" | sudo ufw enable
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
