#!/usr/bin/env bash
# Script to install NGINX in Ubuntu 16
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "y" | sudo ufw enable
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
