#!/usr/bin/env bash
# Script to install NGINX in Ubuntu 16
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sed -i '/error_page 404 /custom_404.html;/a location = /custom_404.html {
                /usr/share/nginx/html;
                internal;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo service nginx restart
