#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -u root --password="$1" --all-databases > backup.sql
filename=$(date +"%d-%m-%y")
sudo tar -zcvf "$filename".tar.gz backup.sql
