#!/usr/bin/env bash
# This script prints to infinity and beyond or I am invicible if tried to kill.
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
