#!/usr/bin/env bash
# Displays numbers from 1 to 100, FizzBuzz, Fizz, Buzz.
i=1
while [ $i -le 100 ]
do
    if [[ $i%5 -eq 0 && $i%3 -eq 0 ]]
    then
	echo "FizzBuzz"
    elif [[ $i%5 -eq 0 ]]
    then
	echo "Buzz"
    elif [[ $i%3 -eq 0 ]]
    then
    	echo "Fizz"
    else
	echo "$i"
    fi
    i=$((i + 1))
done
